=== googleapis/google-cloudevents/jsonschema_out/google/events/firebase/remoteconfig/v1/RemoteConfigEventData.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "version_number": {
            "oneOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "string"
                }
            ],
            "description": "The version number of the version's corresponding Remote Config template."
        },
        "versionNumber": {
            "oneOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "string"
                }
            ],
            "description": "The version number of the version's corresponding Remote Config template."
        },
        "update_time": {
            "type": "string",
            "description": "When the Remote Config template was written to the Remote Config server.",
            "format": "date-time"
        },
        "updateTime": {
            "type": "string",
            "description": "When the Remote Config template was written to the Remote Config server.",
            "format": "date-time"
        },
        "update_user": {
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Display name."
                },
                "email": {
                    "type": "string",
                    "description": "Email address."
                },
                "image_url": {
                    "type": "string",
                    "description": "Image URL."
                },
                "imageUrl": {
                    "type": "string",
                    "description": "Image URL."
                }
            },
            "additionalProperties": true,
            "type": "object",
            "description": "Aggregation of all metadata fields about the account that performed the update."
        },
        "updateUser": {
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Display name."
                },
                "email": {
                    "type": "string",
                    "description": "Email address."
                },
                "image_url": {
                    "type": "string",
                    "description": "Image URL."
                },
                "imageUrl": {
                    "type": "string",
                    "description": "Image URL."
                }
            },
            "additionalProperties": true,
            "type": "object",
            "description": "Aggregation of all metadata fields about the account that performed the update."
        },
        "description": {
            "type": "string",
            "description": "The user-provided description of the corresponding Remote Config template."
        },
        "update_origin": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "integer"
                }
            ],
            "description": "Where the update action originated."
        },
        "updateOrigin": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "integer"
                }
            ],
            "description": "Where the update action originated."
        },
        "update_type": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "integer"
                }
            ],
            "description": "What type of update was made."
        },
        "updateType": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "integer"
                }
            ],
            "description": "What type of update was made."
        },
        "rollback_source": {
            "oneOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "string"
                }
            ],
            "description": "Only present if this version is the result of a rollback, and will be the\n version number of the Remote Config template that was rolled-back to."
        },
        "rollbackSource": {
            "oneOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "string"
                }
            ],
            "description": "Only present if this version is the result of a rollback, and will be the\n version number of the Remote Config template that was rolled-back to."
        }
    },
    "additionalProperties": true,
    "type": "object",
    "description": "The data within all Firebase Remote Config events."
}

=== googleapis/google-cloudevents/testdata/google/events/firebase/remoteconfig/v1/RemoteConfigEventData-simple.json
{
  "versionNumber": "5",
  "updateTime": "2020-11-16T16:35:33.569229Z",
  "updateUser": {
    "name": "Ut ad aute",
    "email": "test@nowhere.com",
    "imageUrl": "http://google.com/favicon.ico"
  },
  "description": "minim reprehenderit Lorem qui proident",
  "updateOrigin": "CONSOLE",
  "updateType": "INCREMENTAL_UPDATE",
  "rollbackSource": 75404139
}
