=== googleapis/google-cloudevents/jsonschema/google/events/cloud/audit/v1/LogEntryData.json
{
  "$id": "google.events.cloud.audit.v1",
  "$schema": "http://json-schema.org/schema",
  "title": "Cloud Audit Log LogEntry v1",
  "name": "LogEntryData",
  "description": "This event is triggered when a new audit log entry is written.",
  "type": "object",
  "goPackage": "auditv1",
  "definitions": {
    "MonitoredResource": {
      "type": "object",
      "description": "The monitored resource that produced this log entry.",
      "properties": {
        "type": {
          "description": "Required. The monitored resource type. For example, the type of a Compute Engine VM instance is `gceInstance`.",
          "type": "string"
        },
        "labels": {
          "description": "Values for all of the labels listed in the associated monitored resource descriptor. For example, Compute Engine VM instances use the labels `\"projectId\"`, `\"instanceId\"`, and `\"zone\"`.",
          "type": "object"
        }
      }
    },
    "ResourceLocation": {
      "type": "object",
      "$comment": "https://cloud.google.com/service-infrastructure/docs/service-control/reference/rpc/google.cloud.audit?hl=en#resourcelocation",
      "description": "Location information about a resource.",
      "properties": {
        "currentLocations": {
          "description": "The locations of a resource after the execution of the operation. Requests to create or delete a location based resource must populate the 'currentLocations' field and not the 'originalLocations' field.",
          "type": "array",
          "items": {
            "type": "string",
            "examples": [
              "europe-west1-a",
              "us-east1",
              "nam3"
            ]
          }
        },
        "originalLocations": {
          "description": "The locations of a resource prior to the execution of the operation. Requests that mutate the resource's location must populate both the 'originalLocations' as well as the 'currentLocations' fields. For example:",
          "type": "array",
          "items": {
            "type": "string",
            "examples": [
              "europe-west1-a",
              "us-east1",
              "nam3"
            ]
          }
        }
      }
    },
    "Status": {
      "type": "object",
      "description": "The status of the overall operation.",
      "properties": {
        "code": {
          "description": "The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].",
          "type": "integer"
        },
        "message": {
          "description": "A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.",
          "type": "string"
        },
        "details": {
          "description": "A list of messages that carry the error details.  There is a common set of message types for APIs to use."
        }
      }
    },
    "ServiceAccountDelegationInfo": {
      "description": "Identity delegation history of an authenticated service account",
      "$comment": "https://cloud.google.com/service-infrastructure/docs/service-control/reference/rpc/google.cloud.audit?hl=en#serviceaccountdelegationinfo",
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "principalEmail": {
              "description": "The email address of a Google account.",
              "type": "string"
            },
            "serviceMetadata": {
              "description": "Metadata about the service that uses the service account.",
              "type": "object"
            }
          }
        },
        {
          "properties": {
            "thirdPartyClaims": {
              "description": "Metadata about third party identity.",
              "type": "object"
            }
          }
        }
      ]
    },
    "AuthenticationInfo": {
      "type": "object",
      "description": "Authentication information for the operation.",
      "$comment": "https://cloud.google.com/service-infrastructure/docs/service-control/reference/rpc/google.cloud.audit?hl=en#google.cloud.audit.AuthenticationInfo",
      "properties": {
        "principalEmail": {
          "type": "string",
          "description": "The email address of the authenticated user (or service account on behalf of third party principal) making the request. For privacy reasons, the principal email address is redacted for all read-only operations that fail with a \"permission denied\" error."
        },
        "authoritySelector": {
          "type": "string",
          "description": "The authority selector specified by the requestor, if any. It is not guaranteed that the principal was allowed to use this authority."
        },
        "thirdPartyPrincipal": {
          "type": "object",
          "description": "The third party identification (if any) of the authenticated user making the request. When the JSON object represented here has a proto equivalent, the proto name will be indicated in the @type property."
        },
        "serviceAccountKeyName": {
          "type": "string",
          "description": "The name of the service account key used to create or exchange credentials for authenticating the service account making the request. This is a scheme-less URI full resource name.",
          "examples": [
            "//iam.googleapis.com/projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}/keys/{key}"
          ]
        },
        "serviceAccountDelegationInfo": {
          "type": "array",
          "description": "Identity delegation history of an authenticated service account that makes the request. It contains information on the real authorities that try to access GCP resources by delegating on a service account. When multiple authorities present, they are guaranteed to be sorted based on the original ordering of the identity delegation events.",
          "items": {
            "$ref": "#/definitions/ServiceAccountDelegationInfo"
          }
        },
        "principalSubject": {
          "type": "string",
          "description": "String representation of identity of requesting party. Populated for both first and third party identities."
        }
      }
    },
    "Resource": {
      "type": "object",
      "properties": {
        "service": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "labels": {
          "type": "object"
        }
      }
    },
    "AuthorizationInfo": {
      "type": "object",
      "$comment": "https://cloud.google.com/service-infrastructure/docs/service-control/reference/rpc/google.cloud.audit?hl=en#authorizationinfo",
      "description": "Authorization information. If there are multiple resources or permissions involved, then there is one AuthorizationInfo element for each {resource, permission} tuple.",
      "properties": {
        "resource": {
          "type": "string",
          "description": "The resource being accessed, as a REST-style string.",
          "examples": [
            "bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID"
          ]
        },
        "permission": {
          "type": "string",
          "description": "The required IAM permission."
        },
        "granted": {
          "type": "boolean",
          "description": "Whether or not authorization for resource and permission was granted."
        },
        "resourceAttributes": {
          "$ref": "#/definitions/Resource",
          "description": "Resource attributes used in IAM condition evaluation. This field contains resource attributes like resource type and resource name. To get the whole view of the attributes used in IAM condition evaluation, the user must also look into AuditLog.requestMetadata.requestAttributes."
        }
      }
    },
    "Auth": {
      "type": "object",
      "properties": {
        "principal": {
          "type": "string"
        },
        "audiences": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "presenter": {
          "type": "string"
        },
        "claims": {
          "type": "object"
        },
        "accessLevels": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Request": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "headers": {
          "type": "object"
        },
        "path": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "scheme": {
          "type": "string"
        },
        "query": {
          "type": "string"
        },
        "time": {
          "type": "string"
        },
        "size": {
          "type": "integer"
        },
        "protocol": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        },
        "auth": {
          "$ref": "#/definitions/Auth"
        }
      }
    },
    "Peer": {
      "type": "object",
      "properties": {
        "ip": {
          "type": "string"
        },
        "port": {
          "type": "integer"
        },
        "labels": {
          "type": "object"
        },
        "principal": {
          "type": "string"
        },
        "regionCode": {
          "type": "string"
        }
      }
    },
    "RequestMetadata": {
      "type": "object",
      "description": "Metadata about the operation.",
      "properties": {
        "callerIp": {
          "type": "string",
          "description":  "The IP address of the caller. For caller from internet, this will be public IPv4 or IPv6 address. For caller from a Compute Engine VM with external IP address, this will be the VM's external IP address. For caller from a Compute Engine VM without external IP address, if the VM is in the same organization (or project) as the accessed resource, `callerIp` will be the VM's internal IPv4 address, otherwise the `callerIp` will be redacted to \"gce-internal-ip\". See https://cloud.google.com/compute/docs/vpc/ for more information.\""
        },
        "callerSuppliedUserAgent": {
          "type": "string",
          "description": "The user agent of the caller. This information is not authenticated and should be treated accordingly."
        },
        "callerNetwork": {
          "type": "string",
          "description": "The network of the caller."
        },
        "requestAttributes": {
          "$ref": "#/definitions/Request",
          "description": "Request attributes used in IAM condition evaluation. This field contains request attributes like request time and access levels associated with the request."
        },
        "destinationAttributes": {
          "$ref": "#/definitions/Peer",
          "description": "The destination of a network activity, such as accepting a TCP connection."
        }
      }
    },
    "AuditLog": {
      "type": "object",
      "description": "The log entry payload, which is always an AuditLog for Cloud Audit Log events.",
      "properties": {
        "serviceName": {
          "type": "string",
          "description": "The name of the API service performing the operation. For example, `\"datastore.googleapis.com\"`."
        },
        "methodName": {
          "type": "string",
          "description": "The name of the service method or operation. For example \"google.datastore.v1.Datastore.RunQuery\""
        },
        "resourceName": {
          "type": "string",
          "description": "The resource or collection that is the target of the operation. For example \"shelves/SHELF_ID/books\""
        },
        "resourceLocation": {
          "$ref": "#/definitions/ResourceLocation",
          "description": "The resource location information."
        },
        "resourceOriginalState": {
          "type": "object",
          "description": "The resource's original state before mutation."
        },
        "numResponseItems": {
          "type": "integer",
          "description": "The number of items returned from a List or Query API method, if applicable."
        },
        "status": {
          "$ref": "#/definitions/Status",
          "description": "The status of the overall operation."
        },
        "authenticationInfo": {
          "$ref": "#/definitions/AuthenticationInfo",
          "description": "Authentication information."
        },
        "authorizationInfo": {
          "type": "array",
          "description": "Authorization information. If there are multiple resources or permissions involved, then there is one AuthorizationInfo element for each {resource, permission} tuple.",
          "items": {
            "$ref": "#/definitions/AuthorizationInfo"
          }
        },
        "requestMetadata": {
          "description": "Metadata about the operation.",
          "$ref": "#/definitions/RequestMetadata"
        },
        "request": {
          "description": "The operation request. This may not include all request parameters, such as those that are too large, privacy-sensitive, or duplicated elsewhere in the log record. It should never include user-generated data, such as file contents. When the JSON object represented here has a proto equivalent, the proto name will be indicated in the `@type` property.",
          "type": "object"
        },
        "response": {
          "type": "object",
          "description": "The operation response. This may not include all response elements, such as those that are too large, privacy-sensitive, or duplicated elsewhere in the log record. It should never include user-generated data, such as file contents. When the JSON object represented here has a proto equivalent, the proto name will be indicated in the `@type` property."
        },
        "metadata": {
          "type": "object",
          "description": "Other service-specific data about the request, response, and other information associated with the current audited event."
        },
        "serviceData": {
          "type": "object",
          "description": "Deprecated, use `metadata` field instead. Other service-specific data about the request, response, and other activities. When the JSON object represented here has a proto equivalent, the proto name will be indicated in the `@type` property."
        }
      }
    },
    "LogEntryOperation": {
      "type": "object",
      "description": "Additional information about a potentially long-running operation with which a log entry is associated.",
      "properties": {
        "id": {
          "type": "string",
          "description": "An arbitrary operation identifier. Log entries with the same identifier are assumed to be part of the same operation."
        },
        "producer": {
          "type": "string",
          "description": "An arbitrary producer identifier. The combination of `id` and `producer` must be globally unique. Examples for `producer`: `\"MyDivision.MyBigCompany.com\"`, `\"github.com/MyProject/MyApplication\"`."
        },
        "first": {
          "type": "boolean",
          "description": "True if this is the first log entry in the operation."
        },
        "last": {
          "type": "boolean",
          "description": "True if this is the last log entry in the operation."
        }
      }
    }
  },
  "properties": {
    "logName": {
      "type": "string",
      "description": "The resource name of the log to which this log entry belongs."
    },
    "resource": {
      "description": "The monitored resource that produced this log entry. Example: a log entry that reports a database error would be associated with the monitored resource designating the particular database that reported the error.",
      "$ref": "#/definitions/MonitoredResource"
    },
    "protoPayload": {
      "description": "The log entry payload, which is always an AuditLog for Cloud Audit Log events.",
      "$ref": "#/definitions/AuditLog"
    },
    "insertId": {
      "description": "A unique identifier for the log entry. ",
      "type": "string"
    },
    "labels": {
      "description": "A set of user-defined (key, value) data that provides additional information about the log entry.",
      "type": "object"
    },
    "operation": {
      "description": "Information about an operation associated with the log entry, if applicable.",
      "$ref": "#/definitions/LogEntryOperation"
    },
    "timestamp": {
      "description": "The time the event described by the log entry occurred.",
      "type": "string"
    },
    "receiveTimestamp": {
      "description": "The time the log entry was received by Logging.",
      "type": "string"
    },
    "severity": {
      "description": "The severity of the log entry.",
      "type": "string"
    },
    "trace": {
      "description": "Resource name of the trace associated with the log entry, if any. If it contains a relative resource name, the name is assumed to be relative to `//tracing.googleapis.com`. Example: `projects/my-projectid/traces/06796866738c859f2f19b7cfb3214824`",
      "type": "string"
    },
    "spanId": {
      "description": "The span ID within the trace associated with the log entry, if any. For Trace spans, this is the same format that the Trace API v2 uses: a 16-character hexadecimal encoding of an 8-byte array, such as `000000000000004a`.",
      "type": "string"
    }
  }
}

=== googleapis/google-cloudevents/examples/binary/audit/LogEntryData-bigqueryjobcompleted.json
{
    "insertId": "1234567",
    "logName": "projects/test-project/logs/cloudaudit.googleapis.com%2Fdata_access",
    "protoPayload": {
      "authenticationInfo": {
        "principalEmail": "robot@test-project.iam.gserviceaccount.com"
      },
      "methodName": "jobservice.jobcompleted",
      "requestMetadata": {
        "callerIp": "2620:15c:0:200:1a75:e914:115b:e970",
        "callerSuppliedUserAgent": "google-cloud-sdk357.0.0 (gzip),gzip(gfe)",
        "destinationAttributes": {},
        "requestAttributes": {}
      },
      "resourceName": "projects/test-project/jobs/sample-job",
      "serviceData": {
        "jobCompletedEvent": {
          "eventName": "query_job_completed",
          "job": {
            "jobConfiguration": {
              "query": {
                "createDisposition": "CREATE_IF_NEEDED",
                "defaultDataset": {},
                "destinationTable": {
                  "datasetId": "sample-dataset",
                  "projectId": "test-project",
                  "tableId": "sample-table"
                },
                "query": "sample-query",
                "queryPriority": "QUERY_INTERACTIVE",
                "statementType": "SELECT",
                "writeDisposition": "WRITE_TRUNCATE"
              }
            },
            "jobName": {
              "jobId": "sample-job",
              "location": "US",
              "projectId": "test-project"
            },
            "jobStatistics": {
              "billingTier": 1,
              "createTime": "2021-11-25T21:55:59.872Z",
              "endTime": "2021-11-25T21:56:00.236Z",
              "queryOutputRowCount": "10",
              "referencedTables": [
                {
                  "datasetId": "sample-dataset-reference",
                  "projectId": "bigquery-samples",
                  "tableId": "full"
                }
              ],
              "startTime": "2021-11-25T21:55:59.956Z",
              "totalBilledBytes": "12345",
              "totalProcessedBytes": "12345",
              "totalSlotMs": "123",
              "totalTablesProcessed": 1
            },
            "jobStatus": {
              "error": {},
              "state": "DONE"
            }
          }
        }
      },
      "serviceName": "bigquery.googleapis.com",
      "status": {}
    },
    "receiveTimestamp": "2021-11-25T21:56:00.653866570Z",
    "resource": {
      "labels": {
        "project_id": "test-project"
      },
      "type": "bigquery_resource"
    },
    "severity": "INFO",
    "timestamp": "2021-11-25T21:56:00.276607Z"
  }

=== googleapis/google-cloudevents/examples/binary/events/cloud/audit/LogEntryData-pubsubCreateTopic.json
{
  "insertId": "9frck8cf9j",
  "logName": "projects/test-project/logs/cloudaudit.googleapis.com%2Factivity",
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "authenticationInfo": {
      "principalEmail": "robot@test-project.iam.gserviceaccount.com",
      "principalSubject": "user:robot@test-project.iam.gserviceaccount.com",
      "serviceAccountKeyName": "//iam.googleapis.com/projects/test-project/serviceAccounts/robot@test-project.iam.gserviceaccount.com/keys/90f662482321f1ca8e82ea675b1a1c30c1fe681f"
    },
    "authorizationInfo": [
      {
        "granted": true,
        "permission": "pubsub.topics.create",
        "resource": "projects/test-project",
        "resourceAttributes": {}
      }
    ],
    "methodName": "google.pubsub.v1.Publisher.CreateTopic",
    "request": {
      "@type": "type.googleapis.com/google.pubsub.v1.Topic",
      "name": "projects/test-project/topics/test-auditlogs-source"
    },
    "requestMetadata": {
      "callerIp": "192.168.0.1",
      "callerNetwork": "//compute.googleapis.com/projects/google.com:my-laptop/global/networks/__unknown__",
      "callerSuppliedUserAgent": "google-cloud-sdk",
      "destinationAttributes": {},
      "requestAttributes": {
        "auth": {},
        "time": "2020-06-30T16:14:47.600710407Z"
      }
    },
    "resourceLocation": {
      "currentLocations": [
        "asia-east1",
        "asia-northeast1",
        "asia-southeast1",
        "australia-southeast1",
        "europe-north1",
        "europe-west1",
        "europe-west2",
        "europe-west3",
        "europe-west4",
        "us-central1",
        "us-central2",
        "us-east1",
        "us-east4",
        "us-west1",
        "us-west2",
        "us-west3",
        "us-west4"
      ]
    },
    "resourceName": "projects/test-project/topics/test-auditlogs-source",
    "response": {
      "@type": "type.googleapis.com/google.pubsub.v1.Topic",
      "messageStoragePolicy": {
        "allowedPersistenceRegions": [
          "asia-east1",
          "asia-northeast1",
          "asia-southeast1",
          "australia-southeast1",
          "europe-north1",
          "europe-west1",
          "europe-west2",
          "europe-west3",
          "europe-west4",
          "us-central1",
          "us-central2",
          "us-east1",
          "us-east4",
          "us-west1",
          "us-west2",
          "us-west3",
          "us-west4"
        ]
      },
      "name": "projects/test-project/topics/test-auditlogs-source"
    },
    "serviceName": "pubsub.googleapis.com"
  },
  "receiveTimestamp": "2020-06-30T16:14:48.401489148Z",
  "resource": {
    "labels": {
      "project_id": "test-project",
      "topic_id": "projects/test-project/topics/test-auditlogs-source"
    },
    "type": "pubsub_topic"
  },
  "severity": "NOTICE",
  "timestamp": "2020-06-30T16:14:47.593398572Z"
}

=== googleapis/google-cloudevents/testdata/google/events/cloud/audit/v1/LogEntryData-bigqueryjobcompleted.json
{
    "insertId": "jpllvgecd7bx",
    "logName": "projects/test-project/logs/cloudaudit.googleapis.com%2Fdata_access",
    "protoPayload": {
      "authenticationInfo": {
        "principalEmail": "robot@test-project.iam.gserviceaccount.com"
      },
      "methodName": "jobservice.jobcompleted",
      "requestMetadata": {
        "callerIp": "2620:15c:0:200:1a75:e914:115b:e970",
        "callerSuppliedUserAgent": "google-cloud-sdk357.0.0 (gzip),gzip(gfe)",
        "destinationAttributes": {},
        "requestAttributes": {}
      },
      "resourceName": "projects/test-project/jobs/bqjob_r3ac45813612fa2d6_0000017d591922c9_1",
      "serviceData": {
        "@type": "type.googleapis.com/google.cloud.bigquery.logging.v1.AuditData",
        "jobCompletedEvent": {
          "eventName": "query_job_completed",
          "job": {
            "jobConfiguration": {
              "query": {
                "createDisposition": "CREATE_IF_NEEDED",
                "defaultDataset": {},
                "destinationTable": {
                  "datasetId": "_1f5a368b27df6124588f6733820599593e869a8a",
                  "projectId": "test-project",
                  "tableId": "anon1f50c147_3e76_44d8_a863_44a8ab3deb61"
                },
                "query": "SELECT * FROM `bigquery-samples`.reddit.full LIMIT 10",
                "queryPriority": "QUERY_INTERACTIVE",
                "statementType": "SELECT",
                "writeDisposition": "WRITE_TRUNCATE"
              }
            },
            "jobName": {
              "jobId": "bqjob_r3ac45813612fa2d6_0000017d591922c9_1",
              "location": "US",
              "projectId": "test-project"
            },
            "jobStatistics": {
              "billingTier": 1,
              "createTime": "2021-11-25T21:55:59.872Z",
              "endTime": "2021-11-25T21:56:00.236Z",
              "queryOutputRowCount": "10",
              "referencedTables": [
                {
                  "datasetId": "reddit",
                  "projectId": "bigquery-samples",
                  "tableId": "full"
                }
              ],
              "startTime": "2021-11-25T21:55:59.956Z",
              "totalBilledBytes": "1450180608",
              "totalProcessedBytes": "1449319174",
              "totalSlotMs": "46",
              "totalTablesProcessed": 1
            },
            "jobStatus": {
              "error": {},
              "state": "DONE"
            }
          }
        }
      },
      "serviceName": "bigquery.googleapis.com",
      "status": {}
    },
    "receiveTimestamp": "2021-11-25T21:56:00.653866570Z",
    "resource": {
      "labels": {
        "project_id": "test-project"
      },
      "type": "bigquery_resource"
    },
    "severity": "INFO",
    "timestamp": "2021-11-25T21:56:00.276607Z"
}

=== googleapis/google-cloudevents/testdata/google/events/cloud/audit/v1/LogEntryData-monitoringCreateTimeSeries.json
{
  "insertId": "1bqg3jae6l3gj",
  "logName": "projects/test-project/logs/cloudaudit.googleapis.com%2Fdata_access",
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "authenticationInfo": {
      "principalEmail": "robot@test-project.iam.gserviceaccount.com",
      "principalSubject": "user:robot@test-project.iam.gserviceaccount.com"
    },
    "authorizationInfo": [
      {
        "granted": true,
        "permission": "monitoring.timeSeries.create",
        "resource": "123456789012",
        "resourceAttributes": {}
      }
    ],
    "methodName": "google.monitoring.v3.MetricService.CreateTimeSeries",
    "request": {
      "@type": "type.googleapis.com/google.monitoring.v3.CreateTimeSeriesRequest",
      "name": "projects/test-project"
      },
    "requestMetadata": {
      "callerIp": "2620:15c:0:200:1a75:e914:115b:e970",
      "callerSuppliedUserAgent": "google-cloud-sdk357.0.0 (gzip),gzip(gfe)",
      "destinationAttributes": {},
      "requestAttributes": {
        "auth": {},
        "time": "2021-11-25T21:56:00.276607Z"
      }
    },
    "resourceName": "projects/test-project",
    "serviceName": "monitoring.googleapis.com"
  },
  "receiveTimestamp": "2021-11-25T21:56:00.653866570Z",
  "resource": {
    "labels": {
      "method": "google.monitoring.v3.MetricService.CreateTimeSeries",
      "project_id": "test-project",
      "service": "monitoring.googleapis.com"
    },
    "type": "audited_resource"
  },
  "severity": "INFO",
  "timestamp": "2021-11-25T21:56:00.276607Z"
}
