=== googleapis/google-cloudevents/jsonschema_out/google/events/firebase/auth/v1/AuthEventData.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "uid": {
            "type": "string",
            "description": "The user identifier in the Firebase app."
        },
        "email": {
            "type": "string",
            "description": "The user's primary email, if set."
        },
        "email_verified": {
            "type": "boolean",
            "description": "Whether or not the user's primary email is verified."
        },
        "emailVerified": {
            "type": "boolean",
            "description": "Whether or not the user's primary email is verified."
        },
        "display_name": {
            "type": "string",
            "description": "The user's display name."
        },
        "displayName": {
            "type": "string",
            "description": "The user's display name."
        },
        "photo_URL": {
            "type": "string",
            "description": "The user's photo URL."
        },
        "photoURL": {
            "type": "string",
            "description": "The user's photo URL."
        },
        "disabled": {
            "type": "boolean",
            "description": "Whether the user is disabled."
        },
        "metadata": {
            "properties": {
                "created_at": {
                    "type": "string",
                    "description": "The date the user was created.",
                    "format": "date-time"
                },
                "createdAt": {
                    "type": "string",
                    "description": "The date the user was created.",
                    "format": "date-time"
                },
                "last_signed_in_at": {
                    "type": "string",
                    "description": "The date the user last signed in.",
                    "format": "date-time"
                },
                "lastSignedInAt": {
                    "type": "string",
                    "description": "The date the user last signed in.",
                    "format": "date-time"
                }
            },
            "additionalProperties": true,
            "type": "object",
            "description": "Additional metadata about the user."
        },
        "provider_data": {
            "items": {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "properties": {
                    "uid": {
                        "type": "string",
                        "description": "The user identifier for the linked provider."
                    },
                    "email": {
                        "type": "string",
                        "description": "The email for the linked provider."
                    },
                    "display_name": {
                        "type": "string",
                        "description": "The display name for the linked provider."
                    },
                    "displayName": {
                        "type": "string",
                        "description": "The display name for the linked provider."
                    },
                    "photo_URL": {
                        "type": "string",
                        "description": "The photo URL for the linked provider."
                    },
                    "photoURL": {
                        "type": "string",
                        "description": "The photo URL for the linked provider."
                    },
                    "provider_id": {
                        "type": "string",
                        "description": "The linked provider ID (e.g. \"google.com\" for the Google provider)."
                    },
                    "providerId": {
                        "type": "string",
                        "description": "The linked provider ID (e.g. \"google.com\" for the Google provider)."
                    }
                },
                "additionalProperties": true,
                "type": "object",
                "description": "User's info at the identity provider"
            },
            "type": "array",
            "description": "User's info at the providers"
        },
        "providerData": {
            "items": {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "properties": {
                    "uid": {
                        "type": "string",
                        "description": "The user identifier for the linked provider."
                    },
                    "email": {
                        "type": "string",
                        "description": "The email for the linked provider."
                    },
                    "display_name": {
                        "type": "string",
                        "description": "The display name for the linked provider."
                    },
                    "displayName": {
                        "type": "string",
                        "description": "The display name for the linked provider."
                    },
                    "photo_URL": {
                        "type": "string",
                        "description": "The photo URL for the linked provider."
                    },
                    "photoURL": {
                        "type": "string",
                        "description": "The photo URL for the linked provider."
                    },
                    "provider_id": {
                        "type": "string",
                        "description": "The linked provider ID (e.g. \"google.com\" for the Google provider)."
                    },
                    "providerId": {
                        "type": "string",
                        "description": "The linked provider ID (e.g. \"google.com\" for the Google provider)."
                    }
                },
                "additionalProperties": true,
                "type": "object",
                "description": "User's info at the identity provider"
            },
            "type": "array",
            "description": "User's info at the providers"
        },
        "phone_number": {
            "type": "string",
            "description": "The user's phone number."
        },
        "phoneNumber": {
            "type": "string",
            "description": "The user's phone number."
        },
        "custom_claims": {
            "properties": {
                "fields": {
                    "additionalProperties": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "object"
                            }
                        ]
                    },
                    "type": "object",
                    "description": "Unordered map of dynamically typed values."
                }
            },
            "additionalProperties": true,
            "type": "object",
            "description": "User's custom claims, typically used to define user roles and propagated\n to an authenticated user's ID token."
        },
        "customClaims": {
            "properties": {
                "fields": {
                    "additionalProperties": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "object"
                            }
                        ]
                    },
                    "type": "object",
                    "description": "Unordered map of dynamically typed values."
                }
            },
            "additionalProperties": true,
            "type": "object",
            "description": "User's custom claims, typically used to define user roles and propagated\n to an authenticated user's ID token."
        }
    },
    "additionalProperties": true,
    "type": "object",
    "description": "The data within all Firebase Auth events"
}

=== googleapis/google-cloudevents/testdata/google/events/firebase/auth/v1/AuthEventData-complex.json
{
  "email": "test@nowhere.com",
  "metadata": {
    "createTime": "2020-05-26T10:42:27Z",
    "lastSignInTime": "2020-05-29T11:00:00Z"
  },
  "providerData": [
    {
      "email": "test@nowhere.com",
      "providerId": "password",
      "uid": "test@nowhere.com"
    }
  ],
  "uid": "UUpby3s4spZre6kHsgVSPetzQ8l2"
}
